import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import './index.css';
import { LoginPage } from './pages/LoginPage';
import { RegisterPage } from './pages/RegisterPage';
import { DashboardPage } from './pages/DashboardPage';
import { CustomersListPage } from './pages/CustomersListPage';
import { CustomerProfilePage } from './pages/CustomerProfilePage';
import { NewCustomerPage } from './pages/NewCustomerPage';
import { PlansPage } from './pages/PlansPage';
import { BillingPage } from './pages/BillingPage';
import { MikrotikPage } from './pages/MikrotikPage';
import { OltPage } from './pages/OltPage';
import { TicketsPage } from './pages/TicketsPage';
import { InventoryPage } from './pages/InventoryPage';
import { MonitoringPage } from './pages/MonitoringPage';
import { NapMapPage } from './pages/NapMapPage';
import { SettingsPage } from './pages/SettingsPage';
import { PlatformAdminPage } from './pages/PlatformAdminPage';
import { AppLayout } from './layouts/AppLayout';
import { RequireAuth } from './lib/RequireAuth';
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterPage, {}) }), _jsxs(Route, { path: "/", element: _jsx(RequireAuth, { children: _jsx(AppLayout, {}) }), children: [_jsx(Route, { index: true, element: _jsx(Navigate, { to: "/dashboard", replace: true }) }), _jsx(Route, { path: "dashboard", element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "clientes", element: _jsx(CustomersListPage, {}) }), _jsx(Route, { path: "clientes/nuevo", element: _jsx(NewCustomerPage, {}) }), _jsx(Route, { path: "clientes/:id", element: _jsx(CustomerProfilePage, {}) }), _jsx(Route, { path: "planes", element: _jsx(PlansPage, {}) }), _jsx(Route, { path: "facturacion", element: _jsx(BillingPage, {}) }), _jsx(Route, { path: "mikrotik", element: _jsx(MikrotikPage, {}) }), _jsx(Route, { path: "olt", element: _jsx(OltPage, {}) }), _jsx(Route, { path: "tickets", element: _jsx(TicketsPage, {}) }), _jsx(Route, { path: "inventario", element: _jsx(InventoryPage, {}) }), _jsx(Route, { path: "monitoreo", element: _jsx(MonitoringPage, {}) }), _jsx(Route, { path: "mapa", element: _jsx(NapMapPage, {}) }), _jsx(Route, { path: "settings", element: _jsx(SettingsPage, {}) }), _jsx(Route, { path: "platform", element: _jsx(PlatformAdminPage, {}) })] })] }) }) }));
